### ISSUE TITLE
How to integrate plugin

### ISSUE THREAD

**Issue by ivansabik** [trac-hacks/trac-oidc#2]
Hi, I just did the whole installation but I dont know how to actually show the users the option to login with oid. Do I need to modify the template to manually include a link or something like that? Thanks

**Comment by dairiki** [comment]
As long as the `trac_oidc.trac_oidc.OidcPlugin` module is enabled (this is normally done by putting a `trac_oidc.* = enabled` line in the `[components]' section of your`trac.ini`,) it should automatically insert a “_Login using Google_” link in the _metanav_ bar (look near the upper right corner of the page).

**Comment by ivansabik** [comment]
Oh I see, I did the install using `pip install trac-oidc`, I already have `trac_oidc.* = enabled` and the json from google in the default conf location, however nothing is showing. I'm using Apache bloodhound BTW not pure trac.
I have already succesfully installed many plugins like custom fields and account manager, any hint? How could I see that it really got installed because it doesnt show up like the other plugins under the Plugins section, cheers.

**Comment by dairiki** [comment]
I don't know anything about _bloodhound_ (other than that it exists,) so I don’t know whether that might be causing trouble.

I assume that you have restarted `tracd`, after installing the plugin.

If the plugin is correctly installed and mentioned in `trac.ini`, it should definitely show up on the _Plugins_ admin page — at least it does for me.

Other than the above hints, I don't really have any other ideas…

**Comment by ivansabik** [comment]
good i appreciate the feedback if I can solve it I'll comment for any other bumping into the same thing
